source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'inherited_resources'
gem 'layout_options', :path => "#{File.expand_path(File.dirname(__FILE__)+'/../../')}"
gem 'rspec'
gem 'rspec-rails'
