source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'inherited_resources', '~> 1.1.2'
gem 'layout_options', :path => "#{File.expand_path(File.dirname(__FILE__)+'/../../')}"
gem 'rspec', '~> 2.1.0'
gem 'rspec-rails', '~> 2.1.0'
